### ISSUE TITLE
can you tell me clearly that  how to modify the given data to the proper format

### ISSUE THREAD

**Issue by zhangyu68** [naver/attention-dialog-embedding#3]
the source code is very helpful to me.But I don't know how to modify the dbdc-3's data. Can you describe it clearly ? Thank you !

**Comment by chan0park** [comment]
Hi,

You should download the official dataset from [dbdc3 webpage](https://dbd-challenge.github.io/dbdc3/datasets), and convert it into two files "dial_list.txt" and "tgt_list.txt"  by yourself. And give the paths for those two files as arguments of readDialog() function to run this code (in [src/utils.py](https://github.com/naver/attention-dialog-embedding/blob/7e21a0413e8a808fd0d70cec41f35b3c3fba87dc/src/utils.py#L89)).

More specifically, this `dial_list.txt` is a list of dialog, and each dialog is a list of utterances. A short snippet of this file could be as follow:
`[[['hi', 'alex'], ['hi'], ['can', 'you', 'say', 'something', 'different'],..., ['zordon', 'he', 'is', 'gone']]]`

For the `tgt_list.txt`file, it should contain the annotation information of each utterance. From the original file, you should count annotations of each utteracne (on whether it's a breakdown or not). The file would look something like this:
`[[[0, 0, 0], [28, 1, 1], [0, 0, 0], [20, 10, 0], [0, 0, 0], ..., [3, 4, 23]]]`
Note that you need [0,0,0] for user's utterance although there's no annotation in the original data, to match the number of entries in `dial_list.txt` and ones in `tgt_list.txt`.

I will close this issue for now, but feel free to reopen this if anything is still unclear for you!
